# Generated by Django 5.2.3 on 2025-06-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(max_length=3)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
            },
        ),
    ]
