# Generated by Django 5.2.3 on 2025-06-21 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['-data'], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='moeda',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='valor',
        ),
        migrations.AddField(
            model_name='cotacao',
            name='data',
            field=models.DateField(default='2025-06-20', help_text='Data da cotação (formato YYYY-MM-DD)', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotacao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 21, 2, 35, 3, 691433, tzinfo=datetime.timezone.utc), help_text='Data e hora do registro/última atualização no banco de dados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotacao',
            name='valor_brl',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor do Dólar em Real (USD/BRL)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='valor_eur',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor do Dólar em Euro (USD/EUR)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='valor_jpy',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor do Dólar em Iene (USD/JPY)', max_digits=10, null=True),
        ),
    ]
